[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
num = "0.4"
xml-rs = "0.8"
http = "1.0.0"
chrono = { version = "0.4", features = ["alloc", "std", "clock"] }
bitfield = "0.14.0"
xmlwriter = "0.1.0"
